name: Cloudflare Clearance Generator

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install nodriver curl_cffi

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Extraction Script
        run: python main.py

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: clearance-data
          path: result.json
